name: Build LLVM GCC2

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref from llvm/llvm-project to build (empty for latest from dev)'
        required: false
        default: ''

jobs:
  determine-ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.determine-ref.outputs.ref }}
    steps:
      - name: Determine Git Ref
        id: determine-ref
        run: |
          if [[ -z "${{ inputs.ref }}" ]]; then
            REF=$(
                git ls-remote https://github.com/trungnt2910/llvm-project \
                    refs/heads/dev/trungnt2910/llvm-gcc2 |                \
                awk '{print $1}'
            )
            echo "Determined latest ref from dev/trungnt2910/llvm-gcc2: $REF"
          else
            REF="${{ inputs.ref }}"
            echo "Using provided ref: $REF"
          fi
          echo "ref=$REF" >> "$GITHUB_OUTPUT"

  stage1:
    needs: determine-ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Create Linux GCC2 Sysroot
        run: |
          pushd ${{ github.workspace }}/scripts
          bash linux-gcc2-sysroot.sh
          popd

      - name: Clone LLVM Project
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project
          pushd ${{ github.workspace }}/llvm-project
          git init
          git remote add origin https://github.com/llvm/llvm-project.git
          git fetch --depth=1 origin "${{ needs.determine-ref.outputs.ref }}"
          git checkout FETCH_HEAD
          popd

      - name: Build Stage 1
        run: |
          pushd ${{ github.workspace }}/llvm-project
          bash ${{ github.workspace }}/scripts/stage1.sh
          popd

      - name: Test Stage 1
        run: |
          pushd ${{ github.workspace }}/llvm-project
          ./build_stage1/bin/llvm-lit -v clang/test/CodeGenCXX/gcc2-abi
          popd

      - name: Package Stage 1
        run: |
          pushd ${{ github.workspace }}
          tar -cvJf stage1.tar.xz -C llvm-project/build_stage1_install .
          popd

      - name: Upload Stage 1 Artifact
        uses: actions/upload-artifact@v7
        with:
          name: stage1
          path: ${{ github.workspace }}/stage1.tar.xz

  stage2:
    needs: [determine-ref, stage1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Create Linux GCC2 Sysroot
        run: |
          pushd ${{ github.workspace }}/scripts
          bash linux-gcc2-sysroot.sh
          popd

      - name: Clone LLVM Project
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project
          pushd ${{ github.workspace }}/llvm-project
          git init
          git remote add origin https://github.com/llvm/llvm-project.git
          git fetch --depth=1 origin "${{ needs.determine-ref.outputs.ref }}"
          git checkout FETCH_HEAD
          popd

      - name: Download Stage 1 Artifact
        uses: actions/download-artifact@v8
        with:
          name: stage1
          path: ${{ github.workspace }}/stage1-download

      - name: Extract Stage 1 Artifact
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project/build_stage1_install
          tar -xvJf ${{ github.workspace }}/stage1-download/stage1.tar.xz -C \
            ${{ github.workspace }}/llvm-project/build_stage1_install

      - name: Build Stage 2
        run: |
          pushd ${{ github.workspace }}/llvm-project
          bash ${{ github.workspace }}/scripts/stage2.sh
          popd

      - name: Test Stage 2
        run: |
          STAGE2_LIB="${{ github.workspace }}/llvm-project/build_stage2_install/lib"
          GCC2_LIB="${{ github.workspace }}/scripts/gcc2/usr/lib"
          export LD_LIBRARY_PATH="$STAGE2_LIB:$GCC2_LIB:$LD_LIBRARY_PATH"

          pushd ${{ github.workspace }}/llvm-project
          ./build_stage2/bin/llvm-lit -v clang/test/CodeGenCXX/gcc2-abi
          popd

      - name: Package Stage 2
        run: |
          pushd ${{ github.workspace }}
          tar -cvJf stage2.tar.xz -C llvm-project/build_stage2_install .
          popd

      - name: Upload Stage 2 Artifact
        uses: actions/upload-artifact@v7
        with:
          name: stage2
          path: ${{ github.workspace }}/stage2.tar.xz

  stage3:
    needs: [determine-ref, stage2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Create Linux GCC2 Sysroot
        run: |
          pushd ${{ github.workspace }}/scripts
          bash linux-gcc2-sysroot.sh
          popd

      - name: Clone LLVM Project
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project
          pushd ${{ github.workspace }}/llvm-project
          git init
          git remote add origin https://github.com/llvm/llvm-project.git
          git fetch --depth=1 origin "${{ needs.determine-ref.outputs.ref }}"
          git checkout FETCH_HEAD
          popd

      - name: Download Stage 2 Artifact
        uses: actions/download-artifact@v8
        with:
          name: stage2
          path: ${{ github.workspace }}/stage2-download

      - name: Extract Stage 2 Artifact
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project/build_stage2_install
          tar -xvJf ${{ github.workspace }}/stage2-download/stage2.tar.xz -C \
            ${{ github.workspace }}/llvm-project/build_stage2_install

      - name: Build Stage 3
        run: |
          pushd ${{ github.workspace }}/llvm-project
          bash ${{ github.workspace }}/scripts/stage3.sh
          popd

      - name: Test Stage 3
        run: |
          # Even though stage 3 bins are built against stage 2 libs,
          # we might want to do this as a sanity check for stage 3 libs.
          STAGE3_LIB="${{ github.workspace }}/llvm-project/build_stage3_install/lib"
          GCC2_LIB="${{ github.workspace }}/scripts/gcc2/usr/lib"
          export LD_LIBRARY_PATH="$STAGE3_LIB:$GCC2_LIB:$LD_LIBRARY_PATH"

          pushd ${{ github.workspace }}/llvm-project
          ./build_stage3/bin/llvm-lit -v clang/test/CodeGenCXX/gcc2-abi
          popd

      - name: Package Stage 3
        run: |
          pushd ${{ github.workspace }}
          tar -cvJf stage3.tar.xz -C llvm-project/build_stage3_install .
          popd

      - name: Upload Stage 3 Artifact
        uses: actions/upload-artifact@v7
        with:
          name: stage3
          path: ${{ github.workspace }}/stage3.tar.xz

  stage3-haiku:
    needs: [determine-ref, stage2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Create Linux GCC2 Sysroot
        run: |
          pushd ${{ github.workspace }}/scripts
          bash linux-gcc2-sysroot.sh
          popd

      - name: Create Haiku GCC2 Sysroot
        run: |
          pushd ${{ github.workspace }}/scripts
          bash haiku-gcc2-sysroot.sh
          popd

      - name: Clone LLVM Project
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project
          pushd ${{ github.workspace }}/llvm-project
          git init
          git remote add origin https://github.com/llvm/llvm-project.git
          git fetch --depth=1 origin "${{ needs.determine-ref.outputs.ref }}"
          git checkout FETCH_HEAD
          popd

      - name: Download Stage 2 Artifact
        uses: actions/download-artifact@v8
        with:
          name: stage2
          path: ${{ github.workspace }}/stage2-download

      - name: Extract Stage 2 Artifact
        run: |
          mkdir -p ${{ github.workspace }}/llvm-project/build_stage2_install
          tar -xvJf ${{ github.workspace }}/stage2-download/stage2.tar.xz -C \
            ${{ github.workspace }}/llvm-project/build_stage2_install

      - name: Build Stage 3 (Haiku Cross)
        run: |
          pushd ${{ github.workspace }}/llvm-project
          bash ${{ github.workspace }}/scripts/stage3.haiku.sh
          popd

      - name: Package Stage 3 (Haiku Cross)
        run: |
          pushd ${{ github.workspace }}
          tar -cvJf stage3.haiku.tar.xz -C llvm-project/build_stage3_install .
          popd

      - name: Upload Stage 3 Artifact (Haiku Cross)
        uses: actions/upload-artifact@v7
        with:
          name: stage3.haiku
          path: ${{ github.workspace }}/stage3.haiku.tar.xz

  release:
    needs: [stage3, stage3-haiku]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

        # TODO: There may be a race condition here if multiple builds complete at the same time.
      - name: Determine Build ID
        id: buildid
        run: |
          latestRev=""
          today=$(date --utc +%Y%m%d)
          releaseUrl="${{ github.server_url }}/${{ github.repository }}/releases/tag/llvm-gcc2-$today."
          pageNum=1
          while [ -z "$latestRev" ];
          do
              json=$(curl -fsSL                                   \
                  -H "Authorization: Bearer ${{ github.token }}"  \
                  -H "Accept: application/vnd.github+json"        \
                  "${{ github.api_url }}/repos/${{ github.repository }}/releases?page=$pageNum")
              pageNum=$((pageNum + 1))
              if [ $(echo $json | jq length) -eq 0 ]; then
                  # This means that we've passed the end and reached an empty array
                  break
              fi
              if [ $(echo $json | jq 'objects // {} | has("message")') == "true" ]; then
                  # API has return an error object
                  echo "Unable to fetch releases from GitHub API"
                  exit 2
              fi
              # Store array of revisions
              revisions=($(echo $json | jq -e -r ".[] | .html_url | select(contains(\"$today\"))[${#releaseUrl}:]")) \
                  || continue
              latestRev=${revisions[0]}
              latestRev=${latestRev%-*}
          done
          if [ -z "$latestRev" ]; then
              latestRev=0
          fi
          latestRev=$((latestRev + 1))
          echo "buildid=$today.$latestRev" >> "$GITHUB_OUTPUT"

      - name: Download Stage 3 Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: stage3*
          merge-multiple: true

      - name: Rename Artifacts for Release
        run: |
          mv stage3.tar.xz llvm-gcc2-${{ steps.buildid.outputs.buildid }}-linux.tar.xz
          mv stage3.haiku.tar.xz llvm-gcc2-${{ steps.buildid.outputs.buildid }}-haiku.tar.xz

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: llvm-gcc2-${{ steps.buildid.outputs.buildid }}
          name: LLVM for GCC2 Binaries Build ${{ steps.buildid.outputs.buildid }}
          make_latest: true
          files: llvm-gcc2-*.tar.xz
